### ISSUE TITLE
 What if the maximum number of hotplug volumes on one vmi is reached?

### ISSUE THREAD

**Issue by haoxiaoci** [kubevirt/csi-driver#114]
**Is your feature request related to a problem? Please describe**:
as i see，we hotplug volumes on virtualmachineinstances, what if the maximum number of hotplug volumes on one vmi is reached?
I think it is unreasonable to limit the number of DVs on infra cluster and the number of PVCs on tenant cluster.

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by awels** [comment]
The practical limit of the number of hotplugged volumes per node is in the several hundred. The theoretical limit is 4M but you will reach other limits well before that. I don't see that as a problem.

I don't really understand the issue here, can you elaborate?
