### ISSUE TITLE
Secret based account tokens on k8s 1.24

### ISSUE THREAD

**Issue by brybacki** [kubevirt/csi-driver#56]
That will not work with k8s 1.24, due to https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token#kep-2799-reduction-of-secret-based-service-account-tokens

_Originally posted by @mfranczy in https://github.com/kubevirt/csi-driver/pull/33#discussion_r959548650_

**Comment by mfranczy** [comment]
One option would be to create a secret of service-account-token type as described here
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token

as mentioned in the KEP it's a non goal to remove explicitly requested tokens:
> Non-Goals
>    * Removal of [explicitly requested secret-based service account tokens](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token).

**Comment by awels** [comment]
Fixed by https://github.com/kubevirt/csi-driver/pull/79 using `kubectl create token` and storing the output and using that to build the infra kubeconfig instead of looking up the token from the SA resource.
