### ISSUE TITLE
Handle DV garbage collection gracefully

### ISSUE THREAD

**Issue by awels** [kubevirt/csi-driver#68]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
CDI and KubeVirt recently introduced DataVolume garbage collection. This means that after the DataVolume completes, the object is garbage collected and the associated PVC becomes the primary object to work with. The code currently assumes that the DV sticks around, which is no longer the case.

**What you expected to happen**:
Properly handle the fact that the DV can be gone, and work with the PVC directly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt CSI version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by davidvossel** [comment]
so either add annotation to keep DV around, or detect if PVC is already populated before creating DV in csi driver controller
